# Generated by Django 5.0.6 on 2024-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(default=None, max_length=1000),
        ),
    ]
